////
Date de création : 18/12/2024 à 11:35
Email : asciidocpro@gmail.
Licence : Framework AsciidocPro © 2024 by Emmanuel Ravrat is licensed under Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
https://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1
###############################################################################
Fichier des attributs de rendu concernant les labels

Ces attributs ont un impact sur ce qui est affiché dans le document

ATTENTION : Ce fichier ne doit contenir aucune ligne vide sauf dans un bloc de
commentaire ou avant un message d'erreur.
###############################################################################
////
////
-------------------------------------------------------------------------------
Labels
-------------------------------------------------------------------------------
////
////
................................................................................
Label à afficher au bout du titre principal lorsque l'attribut `_render_show_correction` est à 1

Valeur : une chaîne de caractères
................................................................................
////
:_render_correction_label: (correction)
////
................................................................................
Titre de la partie "Exercices" qui est créée automatiquement lorsqu'un exercice
est ajouté via l'attribut `_exercises` avec un S depuis un livre.

Valeur : une chaîne de caractères
................................................................................
////
:_render_label_exercises: Exercices